// Seeds the mock backend (localStorage) with a realistic surgical day.
(() => {
  const now = Date.now(), M = 60000;
  const iso = (ms) => new Date(ms).toISOString();
  const hm = (ms) => { const d = new Date(ms); return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0'); };
  const d = new Date(); const p = (n)=>String(n).padStart(2,'0');
  const today = `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;
  const y = new Date(now - 86400000); const yday = `${y.getFullYear()}-${p(y.getMonth()+1)}-${p(y.getDate())}`;
  const checks = {consent:true,hairlineApproved:true,labReports:true,preOpPhotos:true,vitalsCleared:true};
  const teams = () => ({anaesthesia:{leads:["Huzaifa"],assistants:["Luqman","Salman"]},extraction:{members:["Asim","Wahab"]},placing:{hairline:["Huzaifa","Adnan"],middle:["Bilal","Afaq"],crown:["Asim","Wahab"]},arrangement:{members:["Ali Baz","Basit","Zia"]},shower:{members:["Luqman","Salman"]},dressing:{members:["Huzaifa","Adnan","Salman"]}});
  const ph = (s,e) => s==null ? {start:"",end:""} : ({start:hm(s),end:e==null?"":hm(e),startedAt:iso(s),...(e==null?{}:{endedAt:iso(e)})});
  const kase = (o) => ({patient:{name:"",age:"",gender:"",contact:"",bloodGroup:"",allergies:"",medications:""},assessment:{norwoodScale:"",donorDensity:"",recipientArea:"",graftEstimate:"",procedureType:"FUE",notes:""},preOp:{},procedure:{currentPhase:"registration",anaesthesia:{start:"",end:""},extraction:{start:"",end:"",grafts:0},placing:{start:"",end:"",hairline:0,middle:0,crown:0},dressing:{start:"",end:""}},postOp:{prescriptions:"",followUpDate:"",dischargeTime:""},teams:teams(),startTime:"",endTime:"",status:"scheduled",...o});
  const c1 = kase({patient:{name:"Imran Qureshi",age:"34",gender:"Male",contact:"+92 300 1234567",bloodGroup:"B+",allergies:"",medications:""},assessment:{norwoodScale:"IV",donorDensity:"Good",recipientArea:"Hairline, Frontal",graftEstimate:"3200",procedureType:"Nano Sapphire FUE",notes:""},preOp:{...checks,bp:"124/80",pulse:"74",spo2:"98"},startTime:hm(now-130*M),endTime:hm(now+200*M),status:"in-progress"});
  c1.procedure = {currentPhase:"extraction",anaesthesia:ph(now-125*M,now-108*M),extraction:{...ph(now-104*M,null),grafts:2180},placing:{start:"",end:"",hairline:0,middle:0,crown:0},dressing:{start:"",end:""}};
  const c2 = kase({patient:{name:"Bilal Ahmed",age:"41",gender:"Male",contact:"+92 321 5550199",bloodGroup:"O+",allergies:"Penicillin",medications:""},assessment:{norwoodScale:"III Vertex",donorDensity:"Average",recipientArea:"Crown, Mid-scalp",graftEstimate:"2500",procedureType:"DHI",notes:""},preOp:{...checks},status:"in-progress"});
  c2.procedure = {currentPhase:"placing",anaesthesia:ph(now-260*M,now-245*M),extraction:{...ph(now-240*M,now-120*M),grafts:2460},placing:{...ph(now-110*M,null),hairline:900,middle:640,crown:220},dressing:{start:"",end:""}};
  c2.teams.extraction.members=[];
  const c3 = kase({patient:{name:"Hassan Raza",age:"29",gender:"Male",contact:"0333 7788990",bloodGroup:"A+",allergies:"",medications:""},assessment:{norwoodScale:"III",donorDensity:"",recipientArea:"Hairline",graftEstimate:"2200",procedureType:"FUE",notes:""},preOp:{consent:true,hairlineApproved:true,labReports:true,preOpPhotos:false,vitalsCleared:false},startTime:hm(now-40*M)});
  const c4 = kase({patient:{name:"Faisal Khan",age:"38",gender:"Male",contact:"",bloodGroup:"",allergies:"",medications:""},assessment:{norwoodScale:"V",donorDensity:"",recipientArea:"",graftEstimate:"3800",procedureType:"FUT",notes:""},preOp:{...checks},status:"in-progress"});
  c4.procedure = {currentPhase:"placing",anaesthesia:{start:hm(now-300*M),end:hm(now-285*M)},extraction:{start:hm(now-280*M),end:hm(now-12*M),grafts:3650},placing:{start:"",end:"",hairline:0,middle:0,crown:0},dressing:{start:"",end:""}};
  const done = kase({patient:{name:"Usman Tariq",age:"45",gender:"Male",contact:"",bloodGroup:"AB+",allergies:"",medications:""},assessment:{norwoodScale:"IV",donorDensity:"Good",recipientArea:"Hairline",graftEstimate:"2800",procedureType:"FUE",notes:"Smooth case."},preOp:{...checks},status:"completed",postOp:{prescriptions:"Antibiotics 5 days, care kit",followUpDate:today,dischargeTime:hm(now-20*M)}});
  done.procedure = {currentPhase:"postOp",anaesthesia:ph(now-420*M,now-404*M),extraction:{...ph(now-400*M,now-270*M),grafts:2750},placing:{...ph(now-262*M,now-110*M),hairline:1100,middle:1000,crown:650},dressing:ph(now-100*M,now-75*M)};
  const cfg = {staff:["Huzaifa","Luqman","Salman","Asim","Wahab","Adnan","Bilal","Afaq","Ali Baz","Basit","Zia"],rooms:["OT Room 1","OT Room 2","OT Room 3","OT Room 4","OT Room 5"],roomLeads:["Dr. Salman","Huzaifa","","",""],completedCases:[{roomKey:"case5",roomName:"OT Room 5",dischargedAt:hm(now-20*M),dischargedAtIso:iso(now-20*M),record:done}],completedProcedureRooms:[],procedures:["Nano Sapphire FUE","FUE","FUT","DHI","PRP"],checks:[{k:"consent",l:"Consent Form Signed",s:"Patient consent obtained and documented"},{k:"hairlineApproved",l:"Hairline Design Approved",s:"Hairline marking reviewed and signed off"},{k:"labReports",l:"Lab Reports Clear",s:"Blood work and tests within normal range"},{k:"preOpPhotos",l:"Pre-Op Photos Taken",s:"Before photos captured from all angles"},{k:"vitalsCleared",l:"Vitals Cleared",s:"BP, Pulse, SpO2 within safe range"}],procRooms:["Procedure Room 1","Procedure Room 2"],clinicName:"MSK Aesthetics",clinicPhone:"+92 306 5577753",clinicEmail:"info@mskaesthetics.com"};
  const pr1 = {patient:{name:"Ayesha Malik",age:"",gender:"",contact:"0301 2223344",bloodGroup:"",allergies:"",startedAt:iso(now-26*M)},assignee:"Zia",procedure:"PRP",notes:"Session 2 of 3",status:"occupied",queue:[{patient:{name:"Kamran Ali",contact:"0345 1112233",age:"",gender:"",bloodGroup:"",allergies:""},procedure:"PRP",notes:"",addedAt:iso(now-35*M)},{patient:{name:"Sana Javed",contact:"",age:"",gender:"",bloodGroup:"",allergies:""},procedure:"PRP",notes:"Follow-up",addedAt:iso(now-12*M)}]};
  const pr2 = {patient:{name:"",age:"",gender:"",contact:"",bloodGroup:"",allergies:""},assignee:"Basit",procedure:"",notes:"",status:"available",queue:[{patient:{name:"Nadia Hussain",contact:"",age:"",gender:"",bloodGroup:"",allergies:""},procedure:"PRP",notes:"",addedAt:iso(now-8*M)}]};
  const yCase = JSON.parse(JSON.stringify(done)); yCase.patient.name="Zubair Shah";
  const db = {sessions:{[today]:{id:"s1",room_count:5,lead:"Dr. Salman",config:cfg},[yday]:{id:"s0",room_count:4,lead:"Huzaifa",config:{...cfg,completedCases:[{roomKey:"case1",roomName:"OT Room 1",dischargedAt:"14:10",record:yCase}]}}},
    cases:{[today]:{case1:c1,case2:c2,case3:c3,case4:c4},[yday]:{case2:{...c3,patient:{...c3.patient,name:"Waqas Butt"}}}},
    rooms:{[today]:{pr1,pr2},[yday]:{}}};
  localStorage.setItem("msk_mock_db", JSON.stringify(db));
  localStorage.setItem("msk_mock_user", "egk@mskaesthetics.com");
  localStorage.removeItem("msk_ops_journal_v1");
})();
